### ISSUE TITLE
Redesign Footer for Better Visual Impact

### ISSUE THREAD

**Issue by Ctoic** [Ctoic/Lisbook#69] opened 2024-10-13 11:23 UTC
Description: The current footer could be improved to better match the overall design. It should provide useful links and information while being visually attractive.
Tasks:
Add social media icons with hover effects.
Ensure the footer remains sticky at the bottom of the page.
Redesign the typography and layout for better readability.
Include links to important pages (e.g., About, Contact).

**Comment by YakeDev** [comment] 2024-10-13 11:52
Assign me this also, if it is possible

**Comment by Ctoic** [comment] 2024-10-13 11:54
And @YakeDev we can use js to add footer and header dynamically to all pages. If you can add that functionality as well. If you need any help Im here.

**Comment by Samyak137** [comment] 2024-10-13 17:59
I want to work on that, will you please assign it to me.

**Comment by YakeDev** [comment] 2024-10-13 18:12
> And @YakeDev we can use js to add footer and header dynamically to all pages. If you can add that functionality as well. If you need any help Im here.

Hey @Ctoic, I've tried adding the functionality to dynamically insert header and footer on all pages via JavaScript. When I test, everything seems to work fine, but I have a problem with the theme change (Light/Dark). The theme doesn't apply as expected, and I can't pinpoint the cause. If you have any suggestions or ideas, I'd love to hear from you.

**Comment by YakeDev** [comment] 2024-10-13 18:14
Now I want to finish the UI for RDPD page

**Comment by harshitkumargupta** [comment] 2024-10-13 18:18
HI @Ctoic Can you please assign me this issue

**Comment by HKSINGHTHAKUR** [comment] 2024-10-13 18:22
HI @Ctoic 
I kindly request you assign me this issue as a part of hactober fest 2024.
looking forward to do it

**Comment by Ctoic** [comment] 2024-10-13 18:30
@YakeDev if you are working on other issues we can assign this one to the newcommers

**Comment by YakeDev** [comment] 2024-10-13 18:31
I have just a bug,

**Comment by YakeDev** [comment] 2024-10-13 18:32
I'm working on

**Comment by Ctoic** [comment] 2024-10-13 18:33
Okay you can share the deatails with screenshots here @YakeDev

**Comment by Ctoic** [comment] 2024-10-13 18:33
We will debug it togather

**Comment by YakeDev** [comment] 2024-10-13 18:36
> > And @YakeDev we can use js to add footer and header dynamically to all pages. If you can add that functionality as well. If you need any help Im here.
> 
> Hey @Ctoic, I've tried adding the functionality to dynamically insert header and footer on all pages via JavaScript. When I test, everything seems to work fine, but I have a problem with the theme change (Light/Dark). The theme doesn't apply as expected, and I can't pinpoint the cause. If you have any suggestions or ideas, I'd love to hear from you.

@Ctoic I explained Here, Can you please read

**Comment by Ctoic** [comment] 2024-10-13 18:47
Can you share the code snippet or just create a pull request with a different branch i will look at the code and merge it.

**Comment by Ctoic** [comment] 2024-10-13 18:47
@YakeDev

**Comment by YakeDev** [comment] 2024-10-13 20:12
Okay

**Comment by YakeDev** [comment] 2024-10-14 09:06
> Add social media icons with hover effects.
> Ensure the footer remains sticky at the bottom of the page.
> Redesign the typography and layout for better readability.
> Include links to important pages (e.g., About, Contact).
@Ctoic 

HTML

`<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="style.css" />
    <script src="https://cdn.tailwindcss.com"></script>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <title>My Favorite Books Music App</title>
  </head>

  <body
    class="dark-theme bg-gray-900 text-gray-300 d-flex flex-column min-vh-100"
  >
    
    <div id="header-placeholder" class="sticky top-0 z-20"></div>

    
    <div id="footer-placeholder" class="mt-auto"></div>

    
    <script src="./script.js"></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

`

JS

`// Function to load an HTML file into an element
function loadHTML(file, elementId) {
  fetch(file)
    .then((response) => {
      if (!response.ok)
        throw new Error("Erreur lors du chargement du fichier " + file);
      return response.text();
    })
    .then((data) => {
      document.getElementById(elementId).innerHTML = data;
    })
    .catch((error) => console.error(error));
}

// Load header and footer
document.addEventListener("DOMContentLoaded", function () {
  loadHTML("./pages/header.html", "header-placeholder");
  loadHTML("./pages/footer.html", "footer-placeholder");
});`

##The problem is the light/dark button doesn't work

<img width="476" alt="image" src="https://github.com/user-attachments/assets/9f1348f1-75be-4e53-92ac-e94179f9eabc">

**Closed** 2024-10-15 21:03 UTC
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, UI
